apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.Source }}.${{ values.Schema }}.${{ values.Table }}
  description: |
    ${{ values.Description }}
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: user:guest
  lifecycle: POC
