apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.Source }}.${{ values.Schema }}.${{ values.Table }}
  description: |
    ${{ values.Name }}
    
    ${{ values.Description }}
    
    *Note: see TechDocs for full documentation
    
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: user:guest
  system: Portico
  lifecycle: POC
