apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dq-${{ values.Source }}.${{ values.Schema }}.${{ values.Table }}
  description: |
    ${{ values.Name }}
    
    ${{ values.Description }}
    
    *Note: see TechDocs for full documentation
    
  annotations:
    backstage.io/techdocs-ref: dir:.
  tags:
    - structured
  links:
    - url: https://app.bigeye.com/w/142/dashboard
      title: Bigeye Data Observability
      icon: dashboard
      type: admin-dashboard
spec:
  type: DaC
  owner: user:guest
  system: Snowflake-Portico-System
  lifecycle: DMaC V1.0
  dependsOn:
    - resource:Bigeye
  subcomponentOf: tbl-${{ values.Source }}.${{ values.Schema }}.${{ values.Table }}
