---
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: Provider-Domain
  description: Contains all systems managed under the Provider business domain.
spec:
  owner: guests
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: Snowflake-Portico-System
  description: |
    Portico - Snowflake Application with schemas for RAW, WORK, TARGET, and ACCESS.
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  owner: user:guest
  domain: Provider-Domain
  lifecycle: Production
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: Portico-Application-System
  description: |
    Portico - Third Party Application for Provider Data Management.
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  owner: user:guest
  domain: Provider-Domain
  lifecycle: Production
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: Snowflake
  description: Centene's Snowflake Platform
spec:
  type: database
  owner: Team-Skynet
  system: Snowflake-Portico-System
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: Oracle
  description: Oracle Platform
spec:
  type: database
  owner: Team-DBA
  system: Portico-Application-System
---
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: IDMC-MI
  description: CDC Replication Tool from Informatica Data Management Cloud (IDMC), Mass Ingestion (MI) service.
spec:
  type: Tool
  owner: Team-Data-Governance
  system: Snowflake-Portico-System
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: ea_team
spec:
  type: team
  children: []

