apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: DHIaC
  description: Data Hub Ingestion as Code
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: cacorepo1/projects/DaC/services/DHIaC
spec:
  type: service
  owner: user:guest
  lifecycle: experimental
