apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: DHIaC-V1.0
  description: |
    Data Hub Ingestion as Code
    Replicates a table from an application (i.e. Portico) to the EDH (Snowflake).
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: cacorepo1/projects/DaC/services/DHIaC
spec:
  type: service
  owner: user:guest
  lifecycle: experimental
