apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: tx-${{ values.Source }}.${{ values.Schema }}.${{ values.Table }}.${{ values.Step }}
  description: |
    ${{ values.Name }}

    ${{ values.Description }}

    *Note: see TechDocs for full documentation

  annotations:
    backstage.io/techdocs-ref: dir:.
  tags:
    - recommended
    - data
  links:
    - url: https://docs.getdbt.com/docs/introduction
      title: DBT
      icon: documentation
      type: website
spec:
  type: DaC
  owner: user:guest
  system: Snowflake-Portico-System
  lifecycle: DTaC V1.0
  dependsOn:
    - resource:DBT
  subcomponentOf: tbl-${{ values.Source }}.${{ values.Schema }}.${{ values.Table }}
