---
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: Provider-Domain
  description: Contains all systems managed under the Provider business domain.
spec:
  owner: guests
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: Snowflake-Portico-System
  description: |
    Portico - Snowflake Application with schemas for RAW, WORK, TARGET, and ACCESS.
  annotations:
    backstage.io/techdocs-ref: dir:.
  tags:
    - structured
    - centene
  links:
    - url: https://use6.dm-us.informaticacloud.com/mona/ingestion-dashboard
      title: IDMC - Mass Ingestion Dashboard
      icon: dashboard
      type: admin-dashboard
spec:
  owner: user:guest
  domain: Provider-Domain
  lifecycle: Production
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: Portico-Application-System
  description: |
    Portico - Third Party Application for Provider Data Management.
  annotations:
    backstage.io/techdocs-ref: dir:.
  tags:
    - structured
    - centene
spec:
  owner: user:guest
  domain: Provider-Domain
  lifecycle: Production
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: Snowflake
  description: Centene's Snowflake Platform
  tags:
    - structured
    - third-party
spec:
  type: database
  owner: skynet_team
  system: Snowflake-Portico-System
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: Oracle
  description: Oracle Platform
  tags:
    - structured
    - third-party
spec:
  type: database
  owner: dba_team
  system: Portico-Application-System
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: Bigeye
  description: Bigeye Data Observability Platform
  tags:
    - quality
    - third-party
spec:
  type: tool
  owner: dg_team
  system: Portico-Application-System
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: IDMC-MI
  description: CDC Replication Tool from Informatica Data Management Cloud (IDMC), Mass Ingestion (MI) service.
  tags:
    - replication
    - third-party
spec:
  type: Tool
  owner: INFRA_team
  system: Snowflake-Portico-System
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: ea_team
  description: Enterprise Architecture Team provides "internal consulting" services across the enterprise.
spec:
  type: team
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: INFRA_team
  description: Informatica Admin Team provides provides Admin services for several Informatica products.
spec:
  type: team
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: dba_team
  description: DBA Team provides database platform enablement for Oracle, PostgreSQL, and Neo4j.
spec:
  type: team
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: skynet_team
  description: Skynet Team provides platform enablement and cloud engineering expertise to the Centene Data Platform.
spec:
  type: team
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: guest
spec:
  memberOf: [guests]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: cgallisa
spec:
  memberOf: [ea_team]
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: guests
spec:
  type: team
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: dg_team
  description: Data Governance Team ensures data is secure, private, accurate, available, and usable.
spec:
  type: team
  children: []
